"""Seeds real image-based Abstract-reasoning demo questions (Phase 7.5 spec §18), replacing the
Phase 6 text/emoji-only limitation. Images are generated by `scripts/generate_abstract_images.py`
(original CareerOS practice patterns — never downloaded/copyrighted commercial test content) and
served from the local upload directory at the same `/uploads/<path>` URL the admin upload
pipeline produces. Safe to re-run: skips seeding if an image-based abstract question already
exists.

Usage:
    cd backend && python -m scripts.generate_abstract_images   # first, to render the PNGs
    cd backend && python -m scripts.seed_abstract_image_questions
"""

import asyncio

from sqlalchemy import select

from app.core.config import get_settings
from app.db.session import AsyncSessionLocal
from app.models import admin_user, profile, user  # noqa: F401  (resolves cross-model FKs)
from app.models.question import Question, QuestionCategory, QuestionDifficulty, QuestionOption, QuestionTopic
from scripts.generate_abstract_images import generate_all


def _full_url(relative_path: str) -> str:
    settings = get_settings()
    return f"{settings.public_base_url}/uploads/{relative_path}"


async def seed() -> None:
    async with AsyncSessionLocal() as db:
        existing = (
            await db.execute(select(Question).where(Question.question_image_url.like("%/uploads/abstract/%")))
        ).scalars().first()
        if existing is not None:
            print("Image-based abstract demo questions already present — skipping seed.")
            return

        category = (await db.execute(select(QuestionCategory).where(QuestionCategory.slug == "abstract"))).scalar_one_or_none()
        if category is None:
            print("Abstract category not found — run scripts.seed_aptitude_questions first.")
            return

        topics_by_slug = {}
        for row in (await db.execute(select(QuestionTopic).where(QuestionTopic.category_id == category.id))).scalars():
            topics_by_slug[row.slug] = row

        questions = generate_all()
        created = 0
        for entry in questions:
            topic = topics_by_slug.get(entry["topic"])
            question = Question(
                question_text="Study the pattern shown in the image and choose the option that continues it.",
                question_type="IMAGE_BASED",
                question_image_url=_full_url(entry["question_image_url"]),
                question_image_alt_text=entry["question_image_alt_text"],
                category_id=category.id,
                topic_id=topic.id if topic else None,
                difficulty=QuestionDifficulty(entry["difficulty"]),
                explanation="The correct option continues the visual pattern shown in the question image.",
                marks=1.0,
                negative_marks=0.25,
                is_active=True,
                is_demo=True,
            )
            db.add(question)
            await db.flush()

            for order, (option_relative_url, alt_text, is_correct) in enumerate(entry["options"]):
                db.add(
                    QuestionOption(
                        question_id=question.id,
                        option_image_url=_full_url(option_relative_url),
                        option_image_alt_text=alt_text,
                        is_correct=is_correct,
                        display_order=order,
                    )
                )
            created += 1

        await db.commit()
        print(f"Seeded {created} image-based abstract-reasoning demo questions.")


if __name__ == "__main__":
    asyncio.run(seed())
