"""add is_demo flag to companies

Revision ID: 046e44b18c9f
Revises: e4a80fc268db
Create Date: 2026-09-12 19:02:52.961872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046e44b18c9f'
down_revision: Union[str, None] = 'e4a80fc268db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_demo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'is_demo')
    # ### end Alembic commands ###
