"""add media assets, interview recordings, image alt text, and version fields

Revision ID: 1bee777c8a2b
Revises: df9094070d2a
Create Date: 2026-09-13 07:46:05.287655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bee777c8a2b'
down_revision: Union[str, None] = 'df9094070d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('session_question_id', sa.String(length=36), nullable=False),
    sa.Column('local_path', sa.String(length=1024), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('upload_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_question_id'], ['interview_session_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_recordings_session_id'), 'interview_recordings', ['session_id'], unique=False)
    op.create_index(op.f('ix_interview_recordings_session_question_id'), 'interview_recordings', ['session_question_id'], unique=False)
    op.create_index(op.f('ix_interview_recordings_user_id'), 'interview_recordings', ['user_id'], unique=False)
    op.add_column('interview_preparation_progress', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('question_options', sa.Column('option_image_alt_text', sa.String(length=500), nullable=True))
    op.add_column('questions', sa.Column('question_image_alt_text', sa.String(length=500), nullable=True))
    op.add_column('star_stories', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('test_session_questions', sa.Column('question_image_alt_text', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_session_questions', 'question_image_alt_text')
    op.drop_column('star_stories', 'version')
    op.drop_column('questions', 'question_image_alt_text')
    op.drop_column('question_options', 'option_image_alt_text')
    op.drop_column('interview_preparation_progress', 'version')
    op.drop_index(op.f('ix_interview_recordings_user_id'), table_name='interview_recordings')
    op.drop_index(op.f('ix_interview_recordings_session_question_id'), table_name='interview_recordings')
    op.drop_index(op.f('ix_interview_recordings_session_id'), table_name='interview_recordings')
    op.drop_table('interview_recordings')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
