"""add phase 9 admin ops content workflow fields

Revision ID: 2146a3e4995f
Revises: bd5f9ea36fd1
Create Date: 2026-09-13 10:33:11.527734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2146a3e4995f'
down_revision: Union[str, None] = 'bd5f9ea36fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('deep_link', sa.String(length=1024), nullable=True),
    sa.Column('audience', sa.Enum('ALL_USERS', 'COMPANY_FOLLOWERS', 'JOB_MATCH', 'SCHOLARSHIP_INTERESTED', 'SPECIFIC_USER', name='notificationaudience'), nullable=False),
    sa.Column('audience_ref_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENT', 'CANCELLED', name='notificationstatus'), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_admin_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('content_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('source_type', sa.Enum('OFFICIAL_CAREER_PAGE', 'OFFICIAL_NEWSROOM', 'INVESTOR_RELATIONS', 'RSS', 'LEVER', 'ASHBY', 'UNIVERSITY', 'SCHOLARSHIP_PROVIDER', 'GOVERNMENT', 'REGULATOR', 'INDUSTRY_PUBLICATION', 'OTHER', name='sourcetype'), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'VERIFIED', 'FAILING', name='verificationstatus'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovered_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.Enum('JOB', 'SCHOLARSHIP', 'INTELLIGENCE', name='discovereditemtype'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('detected_title', sa.String(length=500), nullable=False),
    sa.Column('detected_company_name', sa.String(length=255), nullable=True),
    sa.Column('original_url', sa.String(length=1024), nullable=False),
    sa.Column('raw_payload_json', sa.JSON(), nullable=False),
    sa.Column('normalized_title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'IGNORED', 'REJECTED', name='discovereditemstatus'), nullable=False),
    sa.Column('created_draft_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_items_normalized_title'), 'discovered_items', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_discovered_items_source_id'), 'discovered_items', ['source_id'], unique=False)
    # Batch mode (spec: SQLite has no ALTER-of-constraints support, so adding a new FK column to
    # an existing table needs the copy-and-move strategy batch mode implements — a plain
    # `add_column`/`create_foreign_key` pair works on Postgres but fails on SQLite dev/test DBs).
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('known_technologies', sa.JSON(), nullable=True))
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_areas', sa.JSON(), nullable=True))
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locations', sa.JSON(), nullable=True))
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_admin_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_companies_created_by_admin_id', 'admin_users', ['created_by_admin_id'], ['id'], ondelete='SET NULL')

    op.add_column('email_connections', sa.Column('last_watch_renewal_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('intelligence_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_publish_at', sa.DateTime(timezone=True), nullable=True))
    with op.batch_alter_table('intelligence_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_admin_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_intelligence_posts_reviewed_by_admin_id', 'admin_users', ['reviewed_by_admin_id'], ['id'], ondelete='SET NULL')
    with op.batch_alter_table('intelligence_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_by_admin_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_intelligence_posts_published_by_admin_id', 'admin_users', ['published_by_admin_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_publish_at', sa.DateTime(timezone=True), nullable=True))
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_admin_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_jobs_reviewed_by_admin_id', 'admin_users', ['reviewed_by_admin_id'], ['id'], ondelete='SET NULL')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_by_admin_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_jobs_published_by_admin_id', 'admin_users', ['published_by_admin_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_publish_at', sa.DateTime(timezone=True), nullable=True))
    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_admin_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_scholarships_reviewed_by_admin_id', 'admin_users', ['reviewed_by_admin_id'], ['id'], ondelete='SET NULL')
    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_by_admin_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_scholarships_published_by_admin_id', 'admin_users', ['published_by_admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scholarships', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scholarships_reviewed_by_admin_id', type_='foreignkey')
        batch_op.drop_constraint('fk_scholarships_published_by_admin_id', type_='foreignkey')
        batch_op.drop_column('published_by_admin_id')
        batch_op.drop_column('reviewed_by_admin_id')
        batch_op.drop_column('scheduled_publish_at')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_published_by_admin_id', type_='foreignkey')
        batch_op.drop_constraint('fk_jobs_reviewed_by_admin_id', type_='foreignkey')
        batch_op.drop_column('published_by_admin_id')
        batch_op.drop_column('reviewed_by_admin_id')
        batch_op.drop_column('scheduled_publish_at')

    with op.batch_alter_table('intelligence_posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_intelligence_posts_published_by_admin_id', type_='foreignkey')
        batch_op.drop_constraint('fk_intelligence_posts_reviewed_by_admin_id', type_='foreignkey')
        batch_op.drop_column('published_by_admin_id')
        batch_op.drop_column('reviewed_by_admin_id')
        batch_op.drop_column('scheduled_publish_at')

    op.drop_column('email_connections', 'last_watch_renewal_at')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_companies_created_by_admin_id', type_='foreignkey')
        batch_op.drop_column('created_by_admin_id')
        batch_op.drop_column('locations')
        batch_op.drop_column('business_areas')
        batch_op.drop_column('known_technologies')
    op.drop_index(op.f('ix_discovered_items_source_id'), table_name='discovered_items')
    op.drop_index(op.f('ix_discovered_items_normalized_title'), table_name='discovered_items')
    op.drop_table('discovered_items')
    op.drop_table('content_sources')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('admin_notifications')
    # ### end Alembic commands ###
