"""add intelligence_posts and company_follows tables

Revision ID: 4166b2e756be
Revises: f183e9a93147
Create Date: 2026-09-12 19:54:28.949951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4166b2e756be'
down_revision: Union[str, None] = 'f183e9a93147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_follows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_follows_company_id'), 'company_follows', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_follows_user_id'), 'company_follows', ['user_id'], unique=False)
    op.create_table('intelligence_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('LEADERSHIP', 'TECHNOLOGY', 'AUTOMATION', 'INVESTMENTS', 'HIRING', 'PROJECTS', 'ACQUISITION', 'PLANT_EXPANSION', 'MANUFACTURING', 'ENERGY', 'FINANCE', 'AI', 'GRADUATE_RECRUITMENT', name='intelligencecategory'), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('post_image_url', sa.String(length=1024), nullable=True),
    sa.Column('image_alt_text', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('relevant_roles', sa.JSON(), nullable=True),
    sa.Column('relevant_skills', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.Enum('OFFICIAL_CAREER_PAGE', 'OFFICIAL_NEWSROOM', 'RSS', 'LEVER', 'ASHBY', 'OTHER', name='sourcetype'), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', 'EXPIRED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_posts_company_id'), 'intelligence_posts', ['company_id'], unique=False)
    op.create_index(op.f('ix_intelligence_posts_slug'), 'intelligence_posts', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intelligence_posts_slug'), table_name='intelligence_posts')
    op.drop_index(op.f('ix_intelligence_posts_company_id'), table_name='intelligence_posts')
    op.drop_table('intelligence_posts')
    op.drop_index(op.f('ix_company_follows_user_id'), table_name='company_follows')
    op.drop_index(op.f('ix_company_follows_company_id'), table_name='company_follows')
    op.drop_table('company_follows')
    # ### end Alembic commands ###
