"""add applications, application_stage_events, application_notes tables

Revision ID: 95be0deefe42
Revises: 4166b2e756be
Create Date: 2026-09-12 21:03:06.248455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95be0deefe42'
down_revision: Union[str, None] = '4166b2e756be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('cv_document_id', sa.String(length=36), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('job_url', sa.String(length=1024), nullable=True),
    sa.Column('current_stage', sa.Enum('SAVED', 'APPLIED', 'APPLICATION_RECEIVED', 'UNDER_REVIEW', 'SHORTLISTED', 'APTITUDE_TEST', 'ASSESSMENT_COMPLETED', 'RECRUITER_SCREEN', 'INTERVIEW', 'FINAL_INTERVIEW', 'ASSESSMENT_CENTRE', 'BACKGROUND_CHECK', 'MEDICAL', 'OFFER', 'HIRED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', 'NO_RESPONSE', name='applicationstage'), nullable=False),
    sa.Column('applied_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('salary', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('cover_letter_text', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cv_document_id'], ['cv_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('application_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_notes_application_id'), 'application_notes', ['application_id'], unique=False)
    op.create_table('application_stage_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.Enum('SAVED', 'APPLIED', 'APPLICATION_RECEIVED', 'UNDER_REVIEW', 'SHORTLISTED', 'APTITUDE_TEST', 'ASSESSMENT_COMPLETED', 'RECRUITER_SCREEN', 'INTERVIEW', 'FINAL_INTERVIEW', 'ASSESSMENT_CENTRE', 'BACKGROUND_CHECK', 'MEDICAL', 'OFFER', 'HIRED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', 'NO_RESPONSE', name='applicationstage'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_stage_events_application_id'), 'application_stage_events', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_stage_events_application_id'), table_name='application_stage_events')
    op.drop_table('application_stage_events')
    op.drop_index(op.f('ix_application_notes_application_id'), table_name='application_notes')
    op.drop_table('application_notes')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
