"""phase 10 monetization reward unlocks and user entitlement

Revision ID: 9ad67addbcef
Revises: b2ff7f49cf7d
Create Date: 2026-09-13 14:31:21.295546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad67addbcef'
down_revision: Union[str, None] = 'b2ff7f49cf7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_unlocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reward_type', sa.Enum('EXTRA_APTITUDE_TEST', 'EXTRA_ATS_ANALYSIS', 'PREMIUM_PRACTICE_SET', 'ADVANCED_REPORT', name='rewardtype'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id', name='uq_reward_unlocks_reference_id')
    )
    op.create_index(op.f('ix_reward_unlocks_user_id'), 'reward_unlocks', ['user_id'], unique=False)
    # Existing rows need a default for this NOT NULL column — server_default backfills them, then
    # is dropped so future inserts must go through the ORM's Python-level default like every other
    # column in this codebase (matches the pattern of every prior CASCADE/column migration here).
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        # Phase 11 Postgres validation: add_column does not emit CREATE TYPE for a native enum
        # (only create_table does), so the type must exist first; and a real database supports
        # ALTER TABLE directly, so SQLite's batch rebuild isn't needed here.
        tier = sa.Enum('FREE', 'PRO', name='subscriptiontier')
        tier.create(bind, checkfirst=True)
        op.add_column('users', sa.Column('subscription_tier', tier, nullable=False, server_default='FREE'))
        op.add_column('users', sa.Column('entitlement_expires_at', sa.DateTime(timezone=True), nullable=True))
        op.alter_column('users', 'subscription_tier', server_default=None)
        return

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'subscription_tier', sa.Enum('FREE', 'PRO', name='subscriptiontier'),
                nullable=False, server_default='FREE',
            )
        )
        batch_op.add_column(sa.Column('entitlement_expires_at', sa.DateTime(timezone=True), nullable=True))
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('subscription_tier', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.drop_column('users', 'entitlement_expires_at')
        op.drop_column('users', 'subscription_tier')
        sa.Enum(name='subscriptiontier').drop(bind, checkfirst=True)
    else:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_column('entitlement_expires_at')
            batch_op.drop_column('subscription_tier')
    op.drop_index(op.f('ix_reward_unlocks_user_id'), table_name='reward_unlocks')
    op.drop_table('reward_unlocks')
    if bind.dialect.name != 'sqlite':
        sa.Enum(name='rewardtype').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
