"""add email tracking connections events oauth states aliases

Revision ID: bd5f9ea36fd1
Revises: 1bee777c8a2b
Create Date: 2026-09-13 09:25:44.245867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5f9ea36fd1'
down_revision: Union[str, None] = '1bee777c8a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('GMAIL', 'OUTLOOK', 'FORWARDED', name='emailprovider'), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_scopes', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REAUTHORIZATION_REQUIRED', 'ERROR', 'DISCONNECTED', name='emailconnectionstatus'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('gmail_history_id', sa.String(length=100), nullable=True),
    sa.Column('gmail_watch_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outlook_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('outlook_subscription_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_email_connection_provider_account')
    )
    op.create_index(op.f('ix_email_connections_user_id'), 'email_connections', ['user_id'], unique=False)
    op.create_table('email_forwarding_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('alias_token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_email_forwarding_aliases_alias_token'), 'email_forwarding_aliases', ['alias_token'], unique=True)
    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('GMAIL', 'OUTLOOK', 'FORWARDED', name='emailprovider'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('recruitment_email_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email_connection_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.Enum('GMAIL', 'OUTLOOK', 'FORWARDED', name='emailprovider'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('provider_thread_id', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('sender_domain', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('evidence_excerpt', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matched_application_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_application_ids', sa.JSON(), nullable=False),
    sa.Column('detected_stage', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_label', sa.String(length=20), nullable=True),
    sa.Column('classification_reason_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'SUGGESTED', 'AMBIGUOUS', 'UNMATCHED', 'CONFIRMED', 'IGNORED', name='recruitmenteventstatus'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['email_connection_id'], ['email_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'provider_message_id', name='uq_recruitment_event_dedup')
    )
    op.create_index(op.f('ix_recruitment_email_events_sender_domain'), 'recruitment_email_events', ['sender_domain'], unique=False)
    op.create_index(op.f('ix_recruitment_email_events_user_id'), 'recruitment_email_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_email_events_user_id'), table_name='recruitment_email_events')
    op.drop_index(op.f('ix_recruitment_email_events_sender_domain'), table_name='recruitment_email_events')
    op.drop_table('recruitment_email_events')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_email_forwarding_aliases_alias_token'), table_name='email_forwarding_aliases')
    op.drop_table('email_forwarding_aliases')
    op.drop_index(op.f('ix_email_connections_user_id'), table_name='email_connections')
    op.drop_table('email_connections')
    # ### end Alembic commands ###
