"""add interview preparation and STAR story tables

Revision ID: df9094070d2a
Revises: ab548a5650f4
Create Date: 2026-09-12 23:33:57.479147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9094070d2a'
down_revision: Union[str, None] = 'ab548a5650f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_question_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_question_categories_slug'), 'interview_question_categories', ['slug'], unique=True)
    op.create_table('interview_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('field', sa.String(length=150), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['interview_question_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_topics_category_id'), 'interview_topics', ['category_id'], unique=False)
    op.create_index(op.f('ix_interview_topics_slug'), 'interview_topics', ['slug'], unique=True)
    op.create_table('star_stories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('SAFETY', 'LEADERSHIP', 'TEAMWORK', 'CONFLICT', 'EQUIPMENT_FAILURE', 'PROBLEM_SOLVING', 'PROCESS_IMPROVEMENT', 'FAILURE_LESSON', 'PRESSURE', 'ACHIEVEMENT', 'CUSTOMER', 'INNOVATION', 'COMMUNICATION', 'DECISION_MAKING', name='starcategory'), nullable=False),
    sa.Column('situation', sa.Text(), nullable=True),
    sa.Column('task', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('lessons', sa.Text(), nullable=True),
    sa.Column('skills_demonstrated', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('company_context', sa.String(length=255), nullable=True),
    sa.Column('relevant_roles', sa.JSON(), nullable=True),
    sa.Column('relevant_questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_star_stories_user_id'), 'star_stories', ['user_id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('field', sa.String(length=150), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('job_role', sa.String(length=150), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('experience_level', sa.Enum('ENTRY', 'JUNIOR', 'MID', 'SENIOR', 'LEAD', 'EXECUTIVE', name='experiencelevel'), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', 'EXPERT', name='interviewdifficulty'), nullable=False),
    sa.Column('answer_guidance', sa.JSON(), nullable=True),
    sa.Column('evaluation_points', sa.JSON(), nullable=True),
    sa.Column('follow_up_prompt', sa.Text(), nullable=True),
    sa.Column('star_tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['interview_question_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['interview_topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_category_id'), 'interview_questions', ['category_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_company_id'), 'interview_questions', ['company_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_field'), 'interview_questions', ['field'], unique=False)
    op.create_index(op.f('ix_interview_questions_industry'), 'interview_questions', ['industry'], unique=False)
    op.create_index(op.f('ix_interview_questions_job_role'), 'interview_questions', ['job_role'], unique=False)
    op.create_index(op.f('ix_interview_questions_topic_id'), 'interview_questions', ['topic_id'], unique=False)
    op.create_table('interview_preparation_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('questions_to_ask', sa.JSON(), nullable=False),
    sa.Column('reviewed_topics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_preparation_progress_application_id'), 'interview_preparation_progress', ['application_id'], unique=False)
    op.create_index(op.f('ix_interview_preparation_progress_user_id'), 'interview_preparation_progress', ['user_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.Enum('PRACTICE', 'MOCK', name='interviewsessionmode'), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='interviewsessionstatus'), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('categories_requested', sa.JSON(), nullable=False),
    sa.Column('time_per_question_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_table('interview_session_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category_slug', sa.String(length=100), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('topic_name', sa.String(length=150), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', 'EXPERT', name='interviewdifficulty'), nullable=False),
    sa.Column('answer_guidance', sa.JSON(), nullable=True),
    sa.Column('evaluation_points', sa.JSON(), nullable=True),
    sa.Column('follow_up_prompt', sa.Text(), nullable=True),
    sa.Column('star_tags', sa.JSON(), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_session_questions_session_id'), 'interview_session_questions', ['session_id'], unique=False)
    op.create_table('interview_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('session_question_id', sa.String(length=36), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.String(length=1024), nullable=True),
    sa.Column('audio_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('self_rating', sa.Integer(), nullable=True),
    sa.Column('used_star', sa.Boolean(), nullable=True),
    sa.Column('gave_measurable_result', sa.Boolean(), nullable=True),
    sa.Column('answered_exact_question', sa.Boolean(), nullable=True),
    sa.Column('is_skipped', sa.Boolean(), nullable=False),
    sa.Column('is_marked_practiced', sa.Boolean(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_question_id'], ['interview_session_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_answers_session_id'), 'interview_answers', ['session_id'], unique=False)
    op.create_index(op.f('ix_interview_answers_session_question_id'), 'interview_answers', ['session_question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_answers_session_question_id'), table_name='interview_answers')
    op.drop_index(op.f('ix_interview_answers_session_id'), table_name='interview_answers')
    op.drop_table('interview_answers')
    op.drop_index(op.f('ix_interview_session_questions_session_id'), table_name='interview_session_questions')
    op.drop_table('interview_session_questions')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_interview_preparation_progress_user_id'), table_name='interview_preparation_progress')
    op.drop_index(op.f('ix_interview_preparation_progress_application_id'), table_name='interview_preparation_progress')
    op.drop_table('interview_preparation_progress')
    op.drop_index(op.f('ix_interview_questions_topic_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_job_role'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_industry'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_field'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_company_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_category_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_star_stories_user_id'), table_name='star_stories')
    op.drop_table('star_stories')
    op.drop_index(op.f('ix_interview_topics_slug'), table_name='interview_topics')
    op.drop_index(op.f('ix_interview_topics_category_id'), table_name='interview_topics')
    op.drop_table('interview_topics')
    op.drop_index(op.f('ix_interview_question_categories_slug'), table_name='interview_question_categories')
    op.drop_table('interview_question_categories')
    # ### end Alembic commands ###
