"""add scholarships and saved_scholarships tables

Revision ID: e4a80fc268db
Revises: 342b98f54b7e
Create Date: 2026-09-12 18:40:53.709071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a80fc268db'
down_revision: Union[str, None] = '342b98f54b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('degree_levels', sa.JSON(), nullable=True),
    sa.Column('fields_of_study', sa.JSON(), nullable=True),
    sa.Column('funding_type', sa.Enum('FULLY_FUNDED', 'PARTIAL', name='fundingtype'), nullable=False),
    sa.Column('tuition_coverage', sa.String(length=255), nullable=True),
    sa.Column('monthly_stipend', sa.String(length=255), nullable=True),
    sa.Column('travel_support', sa.String(length=255), nullable=True),
    sa.Column('insurance_support', sa.String(length=255), nullable=True),
    sa.Column('accommodation_support', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligible_nationalities', sa.JSON(), nullable=True),
    sa.Column('academic_requirements', sa.JSON(), nullable=True),
    sa.Column('experience_requirements', sa.JSON(), nullable=True),
    sa.Column('language_requirements', sa.JSON(), nullable=True),
    sa.Column('age_requirement', sa.String(length=255), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('post_image_url', sa.String(length=1024), nullable=True),
    sa.Column('image_alt_text', sa.String(length=255), nullable=True),
    sa.Column('official_url', sa.String(length=1024), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_type', sa.Enum('OFFICIAL_CAREER_PAGE', 'OFFICIAL_NEWSROOM', 'RSS', 'LEVER', 'ASHBY', 'OTHER', name='sourcetype'), nullable=False),
    sa.Column('source_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', 'EXPIRED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_country'), 'scholarships', ['country'], unique=False)
    op.create_index(op.f('ix_scholarships_slug'), 'scholarships', ['slug'], unique=True)
    op.create_table('saved_scholarships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scholarship_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_scholarships_scholarship_id'), 'saved_scholarships', ['scholarship_id'], unique=False)
    op.create_index(op.f('ix_saved_scholarships_user_id'), 'saved_scholarships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_scholarships_user_id'), table_name='saved_scholarships')
    op.drop_index(op.f('ix_saved_scholarships_scholarship_id'), table_name='saved_scholarships')
    op.drop_table('saved_scholarships')
    op.drop_index(op.f('ix_scholarships_slug'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_country'), table_name='scholarships')
    op.drop_table('scholarships')
    # ### end Alembic commands ###
